### ISSUE TITLE
Important !!

### ISSUE THREAD

**Issue by SimonLeclere** [Morniric/better-instagram.js#3]
Hey, the insta.js library of Androz being open-source, you have the right to modify it and redistribute it as you like, but you have to credit the original author. Instead of reposting the project, make a fork instead ;)

**Comment by Morniric** [comment]
As you can see i haven't changed readme of the project. Androz's libary was using old version of packages i updated them
 i think cant be counted as "reposting" 
But you can teach me how can i credit 
Thank you for review

**Comment by SimonLeclere** [comment]
Yeah I noticed you didn't change anything in the readme or the code! That was more a tip for later ;)
I advise you to write down the changes you made so that users who come on your repo will know why they should use your version instead of the old one.
